<?php

/*
|--------------------------------------------------------------------------
| Tutu generated Routes
|--------------------------------------------------------------------------
|
| This are the routes generated by Tutu.
|
*/

$api = app(Dingo\Api\Routing\Router::class);

$api->version('v1', function ($api) {
    $api->group(['namespace' => 'App\Http\Controllers'], function ($api) {
        // Authentication routes
        $api->group(['namespace' => 'Auth'], function ($api) {
            $api->post('/login', 'AuthController@login');
            $api->post('/register', 'AuthController@register');
        });

        // Resource routes
        $api->get('projects', 'ProjectsController@index');
        $api->post('projects', 'ProjectsController@store');
        $api->get('projects/{project}', 'ProjectsController@show');
        $api->put('projects/{project}', 'ProjectsController@update');
        $api->delete('projects/{project}', 'ProjectsController@destroy');

        $api->get('projects/{task}/tasks', 'TasksController@index');
        $api->post('projects/{task}/tasks', 'TasksController@store');
        $api->get('projects/{task}/tasks/{project}', 'TasksController@show');
        $api->put('projects/{task}/tasks/{project}', 'TasksController@update');
        $api->delete('projects/{task}/tasks/{project}', 'TasksController@destroy');
    });
});
